# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#projects
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  # Finalizer гарантирует, что проект не будет удалён, пока он используется каким-либо приложением
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  description: Project containing infrastructure environment services

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'