apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuber
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development

  source:
    repoURL: https://github.com/PavDev777/react-app.git
    targetRevision: main
    path: react  # <--- каталог, где лежит Chart.yaml
    helm:
      releaseName: react-app
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: reactapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true