- name: Deploy application to Kubernetes using Helm
  hosts: k8s_master
  gather_facts: no

  vars:
    release_name: react-app
    namespace: production
    chart_path: ../react/

  tasks:
    - name: Upgrade Helm release
      community.kubernetes.helm:
        name: "{{ release_name }}"
        chart_ref: "{{ chart_path }}"
        release_namespace: "{{ namespace }}"
        values:
          image:
            repository: "{{ image_name }}"
            tag: "{{ image_tag }}"